# Generated by Django 6.0.4 on 2026-06-09 17:27

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Summer Collection', max_length=100)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.TextField(blank=True)),
                ('button_label', models.CharField(default='Shop Now', max_length=80)),
                ('button_url', models.CharField(default='/shop/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Group',
                'verbose_name_plural': 'Hero Groups',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('section_type', models.CharField(choices=[('featured', 'Featured Products'), ('trending', 'Trending Products'), ('collection', 'Collection')], default='featured', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveIntegerField(default=4)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Overridden by group title if group is set.', max_length=160)),
                ('subtitle', models.TextField(blank=True, help_text='Overridden by group subtitle if group is set.')),
                ('button_label', models.CharField(blank=True, default='Shop Now', max_length=80)),
                ('button_url', models.CharField(blank=True, default='/shop/', max_length=255)),
                ('image', models.FileField(blank=True, upload_to='hero/', validators=[core.validators.validate_store_image])),
                ('image_url', models.URLField(blank=True)),
                ('theme', models.CharField(choices=[('summer', 'Summer Theme'), ('winter', 'Winter Theme'), ('luxury', 'Luxury Theme'), ('festival', 'Festival Theme'), ('streetwear', 'Streetwear Theme')], default='summer', max_length=20)),
                ('animation_type', models.CharField(choices=[('fade', 'Fade In'), ('slide-up', 'Slide Up'), ('scale', 'Scale In'), ('parallax', 'Parallax Effect')], default='fade', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='core.herogroup')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
