# Generated by Django 6.0.4 on 2026-05-20 17:12

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.TextField(blank=True)),
                ('button_label', models.CharField(default='Shop Now', max_length=80)),
                ('button_url', models.CharField(default='/shop/', max_length=255)),
                ('image', models.FileField(blank=True, upload_to='hero/', validators=[core.validators.validate_store_image])),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('section_type', models.CharField(choices=[('featured', 'Featured Products'), ('trending', 'Trending Products'), ('collection', 'Collection')], default='featured', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveIntegerField(default=4)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
