# Generated by Django 6.0.4 on 2026-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="herobanner",
            name="animation_type",
            field=models.CharField(
                choices=[
                    ("fade", "Fade In"),
                    ("slide-up", "Slide Up"),
                    ("scale", "Scale In"),
                    ("parallax", "Parallax Effect"),
                ],
                default="fade",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="herobanner",
            name="theme",
            field=models.CharField(
                choices=[
                    ("summer", "Summer Theme"),
                    ("winter", "Winter Theme"),
                    ("luxury", "Luxury Theme"),
                    ("festival", "Festival Theme"),
                    ("streetwear", "Streetwear Theme"),
                ],
                default="summer",
                max_length=20,
            ),
        ),
    ]
