# Generated by Django 6.0.4 on 2026-06-07 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_herobanner_animation_type_herobanner_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Example: Summer Collection", max_length=100
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("subtitle", models.TextField(blank=True)),
                ("button_label", models.CharField(default="Shop Now", max_length=80)),
                ("button_url", models.CharField(default="/shop/", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hero Group",
                "verbose_name_plural": "Hero Groups",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="button_label",
            field=models.CharField(blank=True, default="Shop Now", max_length=80),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="button_url",
            field=models.CharField(blank=True, default="/shop/", max_length=255),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="subtitle",
            field=models.TextField(
                blank=True, help_text="Overridden by group subtitle if group is set."
            ),
        ),
        migrations.AlterField(
            model_name="herobanner",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Overridden by group title if group is set.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="herobanner",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banners",
                to="core.herogroup",
            ),
        ),
    ]
