# Generated by Django 6.0.4 on 2026-05-20 18:52

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('offer_label', models.CharField(default='Limited Time Offer', max_length=80)),
                ('highlight_text', models.CharField(blank=True, max_length=120)),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('countdown_end', models.DateTimeField(blank=True, help_text='Leave blank to use offer end time.', null=True)),
                ('cta_text', models.CharField(default='Shop Now', max_length=80)),
                ('cta_link', models.CharField(default='/shop/', max_length=255)),
                ('image', models.FileField(blank=True, upload_to='offers/', validators=[core.validators.validate_store_image])),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site_wide', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('floating_ball_enabled', models.BooleanField(default=True)),
                ('permanent_dismiss_allowed', models.BooleanField(default=True)),
                ('display_priority', models.PositiveIntegerField(default=0)),
                ('offer_type', models.CharField(choices=[('site_wide', 'Site-wide'), ('homepage', 'Homepage only'), ('product', 'Product specific'), ('category', 'Category based'), ('trending', 'Trending products'), ('featured', 'Featured products')], default='site_wide', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='assigned_offers', to='products.category')),
                ('products', models.ManyToManyField(blank=True, related_name='assigned_offers', to='products.product')),
            ],
            options={
                'ordering': ['display_priority', '-starts_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='offers_prom_is_acti_c7f8c3_idx'), models.Index(fields=['offer_type', 'display_priority'], name='offers_prom_offer_t_fe42fe_idx')],
            },
        ),
    ]
