# Generated by Django 6.0.4 on 2026-05-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
        (
            "products",
            "0002_sizestock_remove_product_colors_brand_product_brand_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionaloffer",
            name="brands",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_offers", to="products.brand"
            ),
        ),
        migrations.AlterField(
            model_name="promotionaloffer",
            name="offer_type",
            field=models.CharField(
                choices=[
                    ("site_wide", "Site-wide"),
                    ("homepage", "Homepage only"),
                    ("product", "Product specific"),
                    ("category", "Category based"),
                    ("brand", "Brand based"),
                    ("trending", "Trending products"),
                    ("featured", "Featured products"),
                ],
                default="site_wide",
                max_length=20,
            ),
        ),
    ]
