# Generated by Django 6.0.4 on 2026-05-20 17:12

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sizes', models.JSONField(default=list, help_text="Example: ['S', 'M', 'L', 'XL']")),
                ('colors', models.JSONField(blank=True, default=list, help_text="Example: ['Bright Blue', 'Pink Sand']")),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('main_image', models.FileField(blank=True, upload_to='products/main/', validators=[core.validators.validate_store_image])),
                ('image_url', models.URLField(blank=True)),
                ('gallery_image_1', models.FileField(blank=True, upload_to='products/gallery/', validators=[core.validators.validate_store_image])),
                ('gallery_image_2', models.FileField(blank=True, upload_to='products/gallery/', validators=[core.validators.validate_store_image])),
                ('gallery_image_3', models.FileField(blank=True, upload_to='products/gallery/', validators=[core.validators.validate_store_image])),
                ('gallery_url_1', models.URLField(blank=True)),
                ('gallery_url_2', models.URLField(blank=True)),
                ('gallery_url_3', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-is_featured', '-is_trending', 'name'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'), models.Index(fields=['is_active', 'is_trending'], name='products_pr_is_acti_50d29f_idx')],
            },
        ),
    ]
