# Generated by Django 6.0.4 on 2026-06-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_single_color_cloudinary"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color_name",
            field=models.CharField(
                blank=True, help_text="Example: Navy Blue", max_length=50
            ),
        ),
    ]
